id: e10c46b6-5838-4bd7-8870-84c70705e499
version: 3
name: Default_copy
description: Default playbook, Enrich indicators in incident using one or more integrations
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 08854949-08a5-4873-8f01-b3935c78675f
    type: start
    task:
      id: 08854949-08a5-4873-8f01-b3935c78675f
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
  "1":
    id: "1"
    taskid: a8430dac-8cbb-47b3-8a87-2752cab0f36c
    type: condition
    task:
      id: a8430dac-8cbb-47b3-8a87-2752cab0f36c
      version: -1
      name: Should perform enrichment?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "3"
    scriptarguments:
      left: {}
      right: {}
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              complex:
                root: inputs.Enrich
            iscontext: true
          right:
            value:
              simple: "True"
          ignorecase: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
  "2":
    id: "2"
    taskid: 484c0970-2a0a-437f-8328-22f8fc291086
    type: regular
    task:
      id: 484c0970-2a0a-437f-8328-22f8fc291086
      version: -1
      name: Close
      script: Builtin|||closeInvestigation
      type: regular
      iscommand: true
      brand: Builtin
    scriptarguments:
      assetid: {}
      closeNotes: {}
      closeReason: {}
      id: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1040
        }
      }
    note: false
    timertriggers: []
  "3":
    id: "3"
    taskid: 09e4583d-597f-4955-897c-5bb5f24f4f57
    type: title
    task:
      id: 09e4583d-597f-4955-897c-5bb5f24f4f57
      version: -1
      name: Enrich indicators
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 370
        }
      }
    note: false
    timertriggers: []
  "4":
    id: "4"
    taskid: 44e6a83f-14cd-49f4-8c41-0ffde22d3c4f
    type: playbook
    task:
      id: 44e6a83f-14cd-49f4-8c41-0ffde22d3c4f
      version: -1
      name: Extract Indicators - Generic
      description: |-
        Deprecated: We recommend using extractIndicators command instead.
        Extract indicators from input data.
      playbookId: extract_indicators_-_generic
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 515
        }
      }
    note: false
    timertriggers: []
  "5":
    id: "5"
    taskid: 49cd29a6-4a83-44e6-8bdc-86136341411a
    type: playbook
    task:
      id: 49cd29a6-4a83-44e6-8bdc-86136341411a
      version: -1
      name: Entity Enrichment - Generic
      description: Enrich entities using one or more integrations
      playbookId: entity_enrichment_generic
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 690
        }
      }
    note: false
    timertriggers: []
  "6":
    id: "6"
    taskid: 0e467280-8c85-40e6-84a0-4b11305dbcd7
    type: playbook
    task:
      id: 0e467280-8c85-40e6-84a0-4b11305dbcd7
      version: -1
      name: Calculate Severity - Generic
      description: |-
        Calculates and assign the incident severity based on the highest returned severity level from the following severity calculations:

        * Indicators DBotScore - Calculates the incident severity level according to the highest indicator DBotScore.
        * Critical assets - Determines if a critical assest is associated with the invesigation.
        * 3rd-party integrations - Calculates the incident severity level according to the methodology of a 3rd-party integration.

        NOTE: the new severity level overwrites the previous severity level even if the previous severity level was more severe.
      playbookId: Calculate Severity - Generic
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 865
        }
      }
    note: false
    timertriggers: []
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1085,
        "width": 492.5,
        "x": 50,
        "y": 50
      }
    }
  }
inputs:
- key: Enrich
  value:
    simple: "True"
  required: false
  description: Should preform enrichment on all indicators in the incident
outputs: []
